### ISSUE TITLE
Develop documentation and tests for marketplace using storybook

### ISSUE THREAD

**Issue by jmgayosso** [hashed-io/hashed-network-portal-ui#46]
# Tasks

- [x] Added a new plugin on Webpack to solve the IPFS auth issue [Buffer]
- [x] Add new stories using Storybook
- [x] Add the interactions in the stories
- [x] Verify the emitted events
- [x] Load files without a window to choose the file
